/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.hydrogenn;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

/**
 *
 * @author Joshua Davenport
 */
public class LineHandlerServerGUI extends javax.swing.JFrame {

    private List<Problem> problemList = new ArrayList<>();

    /** Creates new form GraphicsHandler */
    public LineHandlerServerGUI() {
        LineHandlerServer server = new LineHandlerServer(this);
        server.start();
        initComponents();
        updateLineLabel();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        solveTopButton = new javax.swing.JButton();
        solveTypeField = new javax.swing.JTextField();
        solveProblemButton = new javax.swing.JButton();
        solveNameButton = new javax.swing.JButton();
        logPanel = new javax.swing.JPanel();
        logLabel = new javax.swing.JLabel();
        linePane = new javax.swing.JScrollPane();
        lineLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        solveTopButton.setText("Solve Top");
        solveTopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solveTopButtonActionPerformed(evt);
            }
        });

        solveTypeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solveTypeFieldActionPerformed(evt);
            }
        });

        solveProblemButton.setText("Solve Problem");
        solveProblemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solveProblemButtonActionPerformed(evt);
            }
        });

        solveNameButton.setText("Solve Name");
        solveNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solveNameButtonActionPerformed(evt);
            }
        });

        logLabel.setForeground(new java.awt.Color(153, 153, 153));
        logLabel.setText("LineMaster™");
        logLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout logPanelLayout = new javax.swing.GroupLayout(logPanel);
        logPanel.setLayout(logPanelLayout);
        logPanelLayout.setHorizontalGroup(
            logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        logPanelLayout.setVerticalGroup(
            logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addContainerGap())
        );

        lineLabel.setText("This text should update automatically. If it doesn't, it's an error.");
        lineLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        linePane.setViewportView(lineLabel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(solveTopButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(solveTypeField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(solveProblemButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(solveNameButton))
                    .addComponent(linePane, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(solveTopButton)
                    .addComponent(solveTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(solveProblemButton)
                    .addComponent(solveNameButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(linePane, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void solveTypeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solveTypeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_solveTypeFieldActionPerformed

    private void solveTopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solveTopButtonActionPerformed
        if (problemList.size() > 0) {
            problemList.remove(0);
            updateLineLabel();
        } else {
            log("There's nothing to remove!");
        }
    }//GEN-LAST:event_solveTopButtonActionPerformed

    private void solveNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solveNameButtonActionPerformed
        if (problemList.size() > 0) {
            List<String> problemNames = new ArrayList<>();
            problemList.stream().forEach((problem) -> {
                problemNames.add(problem.name);
            });
            if (problemNames.contains(solveTypeField.getText())) {
                problemList.stream().filter((problem) -> (problem.name.equalsIgnoreCase(solveTypeField.getText()))).forEach((problem) -> {
                    problemList.remove(problem);
                    updateLineLabel();
                    return;
                });
            } else {
                log("That name doesn't exist! (It has to be exactly the same.)");
            }
        } else {
            log("There's nothing to remove!");
        }
    }//GEN-LAST:event_solveNameButtonActionPerformed

    private void solveProblemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solveProblemButtonActionPerformed
        if (problemList.size() > 0) {
            List<String> problemNames = Problem.getProjects(problemList);
            if (problemNames.contains(solveTypeField.getText())) {
                problemList.stream().filter((problem) -> (problem.project.equalsIgnoreCase(solveTypeField.getText()))).forEach((problem) -> {
                    problemList.remove(problem);
                    updateLineLabel();
                    return;
                });
            } else {
                log("That project doesn't exist! (It has to be exactly the same.)");
            }
        } else {
            log("There's nothing to remove!");
        }
    }//GEN-LAST:event_solveProblemButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LineHandlerServerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LineHandlerServerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LineHandlerServerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LineHandlerServerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LineHandlerServerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lineLabel;
    private javax.swing.JScrollPane linePane;
    private javax.swing.JLabel logLabel;
    private javax.swing.JPanel logPanel;
    private javax.swing.JButton solveNameButton;
    private javax.swing.JButton solveProblemButton;
    private javax.swing.JButton solveTopButton;
    private javax.swing.JTextField solveTypeField;
    // End of variables declaration//GEN-END:variables
  
    void log(String string) {
        logLabel.setForeground(Color.BLACK);
        logLabel.setText(string);
    }

    void addLine(Problem problem) {
        problemList.add(problem);
        updateLineLabel();
    }
    
    void removeLine(Problem problem) {
        problemList.remove(problem);
        updateLineLabel();
    }

    List<Problem> getList() {
        return problemList;
    }

    public void updateLineLabel() {
        lineLabel.setText(Problem.updateLineLabel(problemList));
    }

}
